[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sfg_audiobook"
version = "0.0.1"
dependencies = [
    "openai",
    "pydantic",
    'importlib-metadata; python_version>"3.12"',
]

[project.scripts]
sfg_audiobook = "sfg_audiobook.cli:run_from_cli"