[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sfg_audiobook"
version = "0.0.1"
dependencies = [
    "openai",
    'importlib-metadata; python_version>"3.10"',
]

[project.scripts]
cli-name = "sfg_audiobook.mymodule:some_func"  # TODO